name: OpenRouter
provider_type: openrouter
enabled: true
connection:
  base_url: https://openrouter.ai/api/v1
  api_key_env: OPENROUTER_API_KEY
default_model: tngtech/deepseek-r1t2-chimera:free
defaults:
  temperature: 0.5
extra_headers:
  HTTP-Referer: https://valuecell.ai
  X-Title: ValueCell
models:
- id: anthropic/claude-haiku-4.5
  name: Claude Haiku 4.5
- id: x-ai/grok-4
  name: Grok 4
- id: qwen/qwen3-max
  name: Qwen3 Max
- id: openai/gpt-5
  name: GPT-5
- id: google/gemini-2.5-flash
  name: Gemini 2.5 Flash
- id: google/gemini-3-pro-preview
  name: Gemini 3 Pro Preview
- id: x-ai/grok-4.1-fast
  name: Grok 4.1 Fast(free)
<<<<<<< HEAD
- id: tngtech/deepseek-r1t2-chimera:free
  name: deepseek-r1t2
- id: qwen/qwen3-coder:free
  name: Qwen3 Coder
- id: google/gemini-2.0-flash-exp:free
  name: Gemini 2.0 Flash Experimental (free)
- id: meta-llama/llama-3.3-70b-instruct:free
  name: 'Meta: Llama 3.3 70B Instruct (free)'
=======
- id: google/gemini-2.0-flash-exp:free
  name: google/gemini-2.0-flash-exp:free
>>>>>>> dfa1cdf39017c381122fd2f7b2430540df3ac49e
embedding:
  default_model: qwen/qwen3-embedding-4b
  defaults:
    dimensions: 2560
    encoding_format: float
  models:
  - id: qwen/qwen3-embedding-4b
    name: Qwen3 Embedding 4B
    dimensions: 2560
    max_input: 32768
    description: Qwen3 Embedding Model
